### ISSUE TITLE
Supplemental references

### ISSUE THREAD

**Issue by trvrb** [evogytis/fluB#10] opened 2014-02-19 19:47 UTC
Supplemental Figures and Tables should be directly referenced in the text, i.e. "Figure S1".  Supplemental Figures and Tables should be reordered to reflect the order they are first referenced in the text.  Ideally, all Supplemental Figures and Tables should be referenced from the main text, but this is not completely necessary.  If Supplemental Figures and Tables are not referenced from the main text they should definitely be referenced from the supplemental text.

This is down the road a bit, but keep in mind eLife doesn't do supp. figures.  I solved this by referencing what I would consider supp. figures from the Methods section that appeared at the end of the main text.

**Comment by evogytis** [comment] 2014-02-20 12:10
Seems a bit odd that eLife don't do supplemental stuff. I'll cut down on some of the figures then.
Stuff I think we should keep:
- both LD heatmaps (Figures S1 and S2)
- aSPR and dTMRCA comparisons between and within trees as well as reassortment rate figures (Figures S3-S7)
- either ratios **OR** differences between approximate and exact **normalized** SPR distances (Figures S8-S13)
- robust counting figure S30

Stuff that can probably go:
- correlations between raw and normalized approximate and exact SPR distances (Figures S14-S16 and S23-S25)
- ratios and differences between approximate and exact raw SPR distances (Figures S17-S22)
- MDS figures S26-S29
- overall lineage ratios figures S31, although it helps break down the overall data quite well.

I'll re-order the supp. figures after we've removed the ones we don't need.

**Comment by trvrb** [comment] 2014-02-20 18:31
I presume much of the reason for this is to not bloat the manuscript with figures not central to the main narrative.  The Nature paper with 50 supplemental figures can be difficult to make sense of.

I'd recommend keeping anything that can be directly (and usefully) referenced from the main text / narrative.

**Comment by evogytis** [comment] 2014-02-21 11:55
I think keeping figures referenced in the text is the best idea. I'll do that. 
I don't think it's necessarily a bad idea to have loads of supplementary figures, I consider them as something you look up if you're not convinced by a figure in the main text.

**Comment by evogytis** [comment] 2014-02-21 16:54
Closed via 72991bfce15d696dfefab502935cb07be3c64b58 ?

**Closed as completed by evogytis** 2014-02-21 16:54 UTC

**Comment by trvrb** [comment] 2014-02-21 19:51
Excellent.  BTW you probably already noticed this, but rather than Supplemental Figures, eLife does Figure Supplements (heh).  Like so: http://elife.elifesciences.org/content/2/e00631/F2

So, if there's more detail for a concept already expressed in the main figure it could work well as one of these.

**Comment by evogytis** [comment] 2014-02-22 11:48
I haven't noticed that before, it looks really cool. I'll have a think about whether/what to include as figure supplements.
That figure also reminds me - what shall we do about source code? I don't mind sharing the python code for processing trees (even though it's probably ugly as sin to experienced programmers) and the ipython notebooks for making the figures, but we can't share the sequences since they're from GISAID. Unless someone writes a script to select the same sequences we've used from the GISAID acknowledgement table, any source code included will be useful only to check that everything's coded up right rather than to reproduce the results. Or maybe I'm aiming too high.
